### ISSUE TITLE
Misusing MATLAB function "length"

### ISSUE THREAD

**Issue by renmengye** [Prof-Lu-Cewu/Visual-Relationship-Detection#2]
Hi,

Thanks you for the effort of releasing the source code.
In `top_recall_Relationship.m`, when calculating `num_pos_tuple`, you used 
`length(gt_tuple_label{ii})`. `length` gives the dimension of the longer axis, which results in an erroneous denominator when calculating recall score. Would you consider fix and use `size(gt_tuple_label{ii}, 1)` instead?

**Comment by Prof-Lu-Cewu** [comment]
thanks Mengye Ren

you are right, I found the my result have slight improvement,

I will revise it soon.

---

发件人: Mengye Ren notifications@github.com
发送时间: 2016年8月17日 22:04
收件人: Prof-Lu-Cewu/Visual-Relationship-Detection
主题: [Prof-Lu-Cewu/Visual-Relationship-Detection] Misusing MATLAB function "length" (#2)

Hi,

Thanks you for the effort of releasing the source code.
In top_recall_Relationship.m, when calculating num_pos_tuple, you used
length(gt_tuple_label{ii}). length gives the dimension of the longer axis, which results in an erroneous denominator when calculating recall score. Would you consider fix and use size(gt_tuple_label{ii}, 1) instead?

―

**Comment by renmengye** [comment]
Thanks for the reply. Just a reminder that a same fix will apply to `top_recall_Phrase.m`.

**Comment by Prof-Lu-Cewu** [comment]
have fixed

---

发件人: Mengye Ren notifications@github.com
发送时间: 2016年8月18日 2:34
收件人: Prof-Lu-Cewu/Visual-Relationship-Detection
抄送: Prof-Lu-Cewu; Comment
主题: Re: [Prof-Lu-Cewu/Visual-Relationship-Detection] Misusing MATLAB function "length" (#2)

Thanks for the reply. Just a reminder that a same fix will apply to top_recall_Phrase.m.

―
