### ISSUE TITLE
How can i download the dataset in the paper?

### ISSUE THREAD

**Issue by destinyzs** [Prof-Lu-Cewu/Visual-Relationship-Detection#7]

**Comment by destinyzs** [comment]
ok,i get it

**Comment by fomalhaut-b** [comment]
Hi @destinyzs How did you download the dataset? The link on their webpage seems to be broken.

**Comment by lambda-001** [comment]
I have the same problem.

**Comment by lambda-001** [comment]
@fomalhaut-b  Do you have solved it?
